
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     null,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     pivot,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     claw,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main(){
	//bDisplayDiagnostics=false;
	nMotorEncoder[pivot]=0;
	int UPPER_BOUND = -600;
	//int LOWER_BOUND = 25;
	float tempJoy;

	waitForStart();
	while(true)
	{
		//writeDebugStreamLine("encoder: %d", nMotorEncoder[pivot]);
		//writeDebugStreamLine("val to motor: %f", contMap(tempJoy));
		nxtDisplayCenteredBigTextLine(3,"%d", nMotorEncoder[pivot]);

		if(SensorValue[touch]==1){
			nMotorEncoder[pivot]=0;
		}

		getJoystickSettings(joystick);

		tempJoy = joystick.joy1_y1;
		if(abs(tempJoy)>10){
			tempJoy /= 127.0;
			tempJoy *= 100.0;
			motor[left] = (int)tempJoy;
		}
		else{
			motor[left]=0;
		}
		tempJoy = -joystick.joy1_y2;
		tempJoy = -joystick.joy1_y2;
		if(abs(tempJoy)>10){
			tempJoy /= 127.0;
			tempJoy *= 100.0;
			motor[right]= (int)tempJoy;
		}
		else
		{
			motor[right]=0;
		}
		/*		//ARM {PIVOT)
		if(joy1Btn(6)==1 && nMotorEncoder[pivot]>UPPER_BOUND)
		{	//moving up is negative power
		motor[pivot]=-20;
		}
		else if(joy1Btn(8)==1 && SensorValue[touch]==0)			// && nMotorEncoder[pivot]<LOWER_BOUND)
		{	//moving down is positive power
		motor[pivot]=20;
		}
		else
		{
		motor[pivot]=0;
		}*/
		//CLAW

		if(abs(joystick.joy2_y1)>10)
		{
			motor[claw]=-joystick.joy2_y1/7;
		}
		else{
			motor[claw]=0;
		}
		if(abs(joystick.joy2_y2)>10){
			motor[pivot]=-joystick.joy2_y2/5;
			if(SensorValue[touch]==1&&joystick.joy2_y2<0)
			{
				motor[pivot]=0;

			}
			if(nMotorEncoder[pivot]<UPPER_BOUND&&joystick.joy2_y2>0)
			{
				motor[pivot]=0;
			}
		}
		else
		{
			motor[pivot]=0;
		}

		/*	if(joy1Btn(7)==1)	//open
		{
		motor[claw]=-15;
		}
		else if(joy1Btn(5)==1)	//close
		{
		motor[claw]=15;
		}
		else
		{
		motor[claw]=0;
		}
		FLAG
		*/
		if(joy1Btn(1) == 1)
		{
			PlaySound(soundBlip);
			motor[flag]=100;
		}
		else
		{
			motor[flag]=0;
		}

		if(joy2Btn(4)==1)
		{
			motor[pivot]=-20;
			motor[claw]=1;
			wait1Msec(1000);
		}

	}
}
